# Generated by Django 4.1.7 on 2023-03-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_photo', models.ImageField(default='display-pics/default.jpg', upload_to='display-pics/')),
            ],
        ),
    ]
